#!/bin/sh
set -xa
export PS4='+ ${SECONDS}s + '
date -u
hour=${hour:-`date -u +%H`}
min=${min:-`date -u +%M`}

echo " start running COMMON.TOP "
echo "Current NCO_INGEST version is $nco_ingest_ver"
echo "Current SATINGEST version is $satingest_ver"

########################################
# Check that required variables are set
########################################
set +x
echo
echo envir is ${envir}
echo job is ${job}
echo TASK is ${TASK}
echo
set -x

######################################
# Specify NET, RUN and DATATYPE Names
######################################
export NET=${NET:-ingest}
export RUN=${RUN:-$TASK}
export DATATYPE=${DATATYPE:-${TASK^^}}

###############################
# Create new working directory
###############################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

######################################
# Set job log file for postmsg output
######################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

export pgmout="OUTPUT.$$"

###############################################
# SENDECF  - Flag Events on ECFLOW
# SENDBB   - Allow to talk back to Big Brother
###############################################
export SENDECF=${SENECF:-YES}
export SENDBB=${SENDBB:-YES}

####################################
# Set up ingest related directories
####################################
export USERDIR=${USERDIR:-${DCOMROOT}/ingest_hist}
export TANKDIR=${TANKDIR:-${DCOMROOT}}
export OUTDIR=${OUTDIR:-${DCOMROOT}/ingest_logs}
export BBDIR=${BBDIR:-${COMROOT:?}/logs/bb/ingest}
mkdir -p $USERDIR $TANKDIR $OUTDIR

##########################
# Specify Execution Areas
##########################

# RUN_TYPE used by pgms BUFR_TRANJB and BUFR_TRANMTYPSBT to determine priority
# path directory for bufrtab.XXX files which they read - here set to
# "satingest" so priority path directory is $FIXsatingest and second
# choice (if bufrtab.XXX file not found in $FIXsatingest) is $FIXbufr
# (other choice for RUN_TYPE is "decoder" which reverses priority)
# ----------------------------------------------------------------------------
export RUN_TYPE=${RUN_TYPE:-satingest}

# Paths for obsproc_shared_bufr_cword items
# -----------------------------------------
export EXECobsproc_shared_bufr_cword=$CWORDX
export USHobsproc_shared_bufr_cword=$CWORDush
export TRANJBush=$TRANush

# Paths for non-obsproc items
# ---------------------------
# ... $FIXsatingest is  populated with all of the bufrtab.XXX
#     files read by bufr_tranjb.sh and ingest_translate_orbits.sh, so to be
#     safe the second choice directory path to retrieve these files ($FIXbufr)
#     is being exported as /dev/null - the reasoning being that it is better
#     for the jobs to fail than to read a bufrtab.XXX that might be obsolete
#     if, for some bizarre reason, the bufrtab.XXX files are not found in
#     $FIXsatingest.
# ... $FIXsatingest is also populated with $TASK and $TASK.$family
#     files read by JISATINGEST.
#     -------------------------------------------------------------------------
export FIXbufr=/dev/null

################################################################
# Copy utility scripts for bufr_tranjb - will remove once bufr_tranjb updated?
################################################################
cp $UTILROOT/ush/finddate.sh   .; chmod +x finddate.sh
cp $UTILROOT/ush/err_chk   .; chmod +x err_chk
cp $UTILROOT/ush/err_exit  .; chmod +x err_exit
cp $UTILROOT/ush/prep_step .; chmod +x prep_step
cp $UTILROOT/ush/postmsg   .; chmod +x postmsg
cp $UTILROOT/ush/startmsg .; chmod +x startmsg
cp $UTILROOT/ush/setpdy.sh .; chmod +x setpdy.sh
##########################################

export DECDROOT=${DECDROOT:-$OPSROOT/decoders}
export USHbufr=${USHbufr:-$DECDROOT/decod_dcncld/ush}

export DCNCLD=${DCNCLD:-$DECDROOT/decod_dcncld/exec/decod_dcncld}

####################################
# Set-up ingest processing families
####################################

export MACHINE=${PDA_SERVER:-140.90.190.143}
export TRANSFER_COMMAND=${TRANSFER_COMMAND:-lftp}
export HISTLENMIN=450
export HISTLENMAX=600
export HOURS2ALARM=6
export ndayarch=3
export DELAFTPROC=YES
export TANKPROTECT=NO
export DEBUGSCRIPTS=ON

export ngroup=1

#export machine=WCOSS

# CLAVR synoptic data 
#---------------------------------------
export ORBITLIST1=clavr.synop.hrlylist
export REMOTEDSNGRP1="PDAFileLinks/PULL/GRIB/clavrx_??_??_?_????_???.cell.hdf"
export FTYPE1=NONE
export TANKFILE1=wgrbbul
export EXECUTE1=ingest_clavr.sh
export BUFRTABLE1=none
export FORGNTABLE1=noforgntable

#######################################################################
# whild most ingest jobs share ush/exec/fix with satingest, icloud
# needs some scripts/tables which could not fine in satingest. 
# For those files, looking for them under $PACKAGEROOT/nco_ingest.$ver/.
#######################################################################
export HOMEbufr=${HOMEnco_ingest}
export TABLEDIR=${HOMEnco_ingest}/fix
export EXECbufr=$HOMEbufr/exec
export FIXbufr=$HOMEbufr/fix
export USHbufr=$HOMEbufr/ush
export USHobsproc_satingest=$HOMEbufr/ush
export EXECobsproc_satingest=$HOMEbufr/exec

env

###################################################
# Execute the script
###################################################
${HOMEbufr}/scripts/existore.sh

if [ $KEEPDATA != "YES" ];
then
   rm -rf $DATA
fi

date
exit
